version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  customer:
    network_mode: host
    build: 
      context: ./customer
    ports:
      - 8080:8080
    depends_on:
      - mongo
