version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  consul:
      image: consul
      ports:
        - 8500:8500
  customer:
    network_mode: host
    build: 
      context: ./customer
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - consul
  customerfidelity: 
    network_mode: host
    build: 
      context: ./customerfidelity
    ports:
      - 8081:8081
    depends_on:
      - consul
      - customer
